spring:
  datasource:
    url: jdbc:h2:mem:database
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
toss:
  payments:
    base-url: https://api.tosspayments.com
    api:
      confirm-url: /v1/payments/confirm
      refund-url-template: /v1/payments/{paymentKey}/cancel
